##########
# Only fill out the Values of this yaml-file.
# As per yaml-syntax indentation matters but within an indentation block the order of the "key: value" pairs does not.
# The general order of each section has to be edited in the templates/ directory and not in this file.
##########


page: # general (meta-) information used mostly in the html header
  html_title: participatory resilience
  html_author: COSS@ETHZ
  html_description: hackathon, renewable, computational
  # search terms that are good for SEO
  logo: navbar-logo.svg
  

title:
  heading: Participatory Resilience
  subheading: Empower Society with Social IoT from 05. to 09.09.
  button_text: Learn more!
  registration_text: Sign up now!
  image: title/network_blue.jpg
  description:
    heading: About this hackathon
    text: |
      This is a Block Course for ETH students that is organized as a hackathon. It will allow students to showcase their innovative spirit through different projects. The fast-paced structure of the course produces an atmosphere of creativity and collaboration as makers work in teams of up to five to create their product. Teams will be provided with easy-to-use technology (RaspberryPi, Arduino, etc.), tools, materials, co-working space and mentorship to turn their ideas into reality. Presenters' material will be published on moodle: https://moodle-app2.let.ethz.ch/course/view.php?id=18111
  countdown:
    date: September 5, 2022 0:00:00 # parsed by javascript. Keep this exact date format
    text: Starts in
    isover: Hackathon is over! Join us next time.


section1:
  title: Highlights
  subtitle: What is in for you?
  content_items:
    - title: Open-source innovation
      description: Build a more resilient tomorrow
      fa_icon: code-branch
    - title: Earn 3 ECTS in 5 days
      description: 40 Semesterwochenstunden
      fa_icon: graduation-cap
    - title: Networking
      description: Kick-off new ideas and projects
      fa_icon: map-pin


section2:
  title: Challenges
  subtitle: You will work on the following topics
  content_items:
    - title: IoT Prototyping
      subtitle: Prototyping a sensing device for crowdsouricng environmental data
      image: challenges/iot.jpeg
      description: Traditional environmental monitoring methods typically rely on fixed monitoring stations, which are costly to set up and maintain. Although the data obtained from such stations is reliable, the spatial resolution is limited due to the small number of such stations. Because of advances in low-cost sensors and the availability of off-the-shelf hardware, it is now possible to build low-cost environmental monitoring devices using do-it-yourself (DIY) methods. Such devices not only increase data availability, but also allow for the use of low-cost sensors to complement official environmental monitoring systems. This challenge will revolve around the development of an open-source environmental monitoring IoT device using microprocessors, microcontrollers, sensors, and other materials that can potentially be used for crowdsourcing environmental data. Information about the design and development of an environmental monitoring IoT device is shared for motivation and to give participating teams a head start. The current prototype is modular in design and has a variety of functionalities ranging from particulate matter measurement to light intensity measurement. Teams can either improve the usability of an existing sensing device by improving the current hardware configuration or adding new functionalities, or they can develop a new prototype.
    - title: Digital Fabrication
      subtitle: Digital design and manufacturing of parts and components for IoT devices
      description: "3D printing has revolutionized the way people create products for personal and commercial use. It is now much easier for businesses and individuals to turn their ideas into reality without having to spend a lot of money. This challenge will revolve around designing and creating new 3D printing models and products. You can either use or start from an existing 3D model or CAD software and send them to your 3D printing facility for printing. We have developed a basic CAD model for the enclosure for an IoT device. How can it be made more user friendly and sustainable? How can the design be made more modular to allow it to be used for different scenarios, for example: indoor/outdoor environmental sensing, mobile sensing, etc."
      image: challenges/3d.jpeg
    - title: Data Representation
      subtitle: Data visualization is critical in "making sense of data."
      description: "A critical part when dealing with a large volume of data is how to make sense of the data in a way that it can be easily understanable by experts as well as non-experts. The goal of this challenge is to provide an intuitive and efficient method of visualizing and communicating data. Storytelling with data can improve contextual understanding as well as facilitate action. The current version of the IoT device displays color coded data on the LED screen to provide visual feedback. The data from the device can be also be visualized in real-time on visualization streams. The goal of this task would be to improve the data representation. The teams could focus on issues (not limited to) such as: Which data does the user want to see? How can it be presented in a user-friendly manner on the device as well as on the data visualization platform? Which representation results in behavior change?"
      image: challenges/datarep.jpeg
    - title: Data Analytics
      subtitle: Data Science techniques have changed the way we handle sensor data.
      description: Several data science tools and packages are available that can be used to get insights from heterogeneous and unstructured sensor data. These tools can be used to create open-source cross-platform applications that enable both novices and experts to clean, visualize, interpret, and statistically analyze their data in meaningful ways. We created the exploreR (RShiny-based) application, which allows users to do a visual inspection of data and perform several data analysis tasks. The goal of this challenge is to either improve the application's functionality or create a new user-friendly application that allows for easy analysis of sensor data.
      image: challenges/analytics.jpeg
    - title: Data Integration
      subtitle: Integrating data from multiple sources to expand scope
      description: There is an abundance of open-source datasets that can be easily accessed and used to create new services and applications. Data integration not only improves the scope of existing applications but also allow creation of new frameworks (dashboards, applications, etc.) that can create new unexpected insights. The challenge would be to think about innovative ways in which the sensor data can enrich other datasets by adding new dimensions. 
      image: challenges/integration.jpeg
    - title: Ad-hoc networks
      subtitle: Ad-hoc networks for communication during disasters
      description: An almost empty phone can mean the difference between life and death in a disaster. On any given day communication using mobile phones requires functional infrastructure, however what happens when the infrastructure is gone due to a disaster. How do people seek information and collaborate to survive? Ad-hoc networks can be used to create dynamic and decentralised communication networks. Their applications range from messaging apps (such as firechat, that was able to avoid governmental censorship in the Arab Spring protests), improving Internet coverage or crisis  management in catastrophes. These networks can serve as a backbone to a new paradigm of participatory resilient societies. This challenge will revolve around thinking of innovative ideas to create solutions with Ad-Hoc networks for promoting disaster resilience.  A potnetial application could be mobile application that leads to the formation of a scale-free loop-free mobile ad hoc network that is context-aware and delivery participatory fairness. You can find more information in the resources.
      image: challenges/network.jpg
      
section3:
  title: Agenda
  subtitle: What happens when
  content_items:
    - title: Day 1 (Mo. 05.09.2022)
      subtitle: Welcome
      content_items:
        - name: Welcome @ETF E1!
          start: "8:45"
          end: "9:00"
        - name: Dirk Helbing—introduction
          start: "9:00"
          end: "9:30"
        - name: Orga team—organizational points
          start: "9:30"
          end: "10:00"
        - name: Rosy Mondardini—co-creation and citizen science
          start: "10:00"
          end: "10:30"
        - name: coffee @polysnack
          start: "10:30"
          end: "11:00"
        - name: Sachit Mahajan and Javier Argota—IoT and Data Integration workshop
          start: "11:00"
          end: "12:30"
        - name: Lunch
          start: "12:30"
          end: "13:30"
        - name: Indushree Banerjee—emergency communication
          start: "13:30"
          end: "14:30"
        - name: name your gadget
          start: "14:30"
          end: "15:00"
        - name: coffee @polysnack
          start: "15:00"
          end: "15:30"
        - name: explore facility/gadget activity
          start: "15:30"
          end: "16:30"
        - name: get to know your lecturers
          start: "16:30"
          end: "17:00"
      image: timeline/welcome.jpg
    - title: Day 2 (Tu. 06.09.2022)
      subtitle: Team up!
      content_items:
        - name: Lilian Blaser
          start: "09:00"
          end: "09:30"
        - name: Evangelos Pournaras (online)
          start: "09:45"
          end: "10:30"
        - name: coffee @polysnack
          start: "10:30"
          end: "11:00"
        - name: Tobias Luthe (online)
          start: "11:00"
          end: "11:30"
        - name: Christoph Laib—ideation phase
          start: "11:30"
          end: "12:30"
        - name: lunch
          start: "12:30"
          end: "13:30"
        - name: Christoph Laib—team building
          start: "13:30"
          end: "14:30"
        - name: team up and research ideas
          start: "14:30"
          end: "15:00"
        - name: coffee @polysnack
          start: "15:00"
          end: "15:30"
        - name: pitch your ideas 10x20 (Pecha Kucha)
          start: "15:30"
          end: "17:00"
      image: timeline/teambuilding.jpg
    - title: Day 3 (We. 07.09.2022)
      subtitle: Implementation
      content_items:
        - name: Thomas Maillart
          start: "9:00"
          end: "10:30"
        - name: coffee @polysnack
          start: "10:30"
          end: "11:00"
        - name: develop project
          start: "11:00"
          end: "12:30"
        - name: lunch
          start: "12:30"
          end: "13:30"
        - name: develop project
          start: "14:00"
          end: "15:00"
        - name: Chris Salter—Design and Computation Arts
          start: "14:30"
          end: "15:00"
        - name: coffee @polysnack
          start: "15:00"
          end: "15:30"
        - name: develop project
          start: "15:30"
          end: "17:00"
      image: timeline/coding.jpg
    - title: Day 4 (Th. 08.09.2022)
      subtitle: Implementation
      content_items:
        - name: develop project
          start: "9:00"
          end: "10:30"
        - name: coffee @polysnack
          start: "10:30"
          end: "11:00"
        - name: develop project
          start: "11:00"
          end: "14:30"
        - name: present your project updates
          start: "14:30"
          end: "15:00"
        - name: coffee @polysnack
          start: "15:00"
          end: "15:30"
        - name: develop project
          start: "15:30"
          end: "17:00"
      image: timeline/coding.jpg
    - title: Day 5 (Fr. 09.09.2022)
      subtitle: Present your work
      content_items:
        - name: finalize project
          start: "09:00"
          end: "11:30"
        - name: coffee @polysnack
          start: "10:30"
          end: "11:00"
        - name: prepare demo
          start: "10:30"
          end: "13:00"
        - name: demo
          start: "13:00"
          end: "14:30"
        - name: panel
          start: "14:00"
          end: "14:30"
        - name: winner ceremony
          start: "14:30"
          end: "15:00"
        - name: Apéro @polysnack
          start: "15:00"
          end: "16:00"
      image: timeline/presentation.jpg
  timeline_conclusion_text: "Be part <br/> of social <br/> IoT!" # needs a little fiddling with line breaks


section4:
  title: Experts you will meet.
  subtitle: These experts will provide insights and support for your project.
  description: Don't miss the opportunity to get to know them after their keynotes!
  content_items:
    - name: Dirk Helbing
      role: Professor for Computational Social Science
      image: experts/helbing.jpeg
      twitter: https://twitter.com/DirkHelbing
      linkedin: https://ch.linkedin.com/in/dirk-helbing-58b291b1
    - name: Rosy Mondardini
      role: Citizen Science Center
      image: experts/rosy.jpg
      twitter: https://twitter.com/rosymond
      linkedin: https://www.linkedin.com/in/rosy-mondardini/
    - name: Indushree Banerjee
      role: TU Delft
      image: experts/indushree.jpg
      twitter: https://twitter.com/sosbanerjee
      linkedin: https://www.linkedin.com/in/indushree-banerjee-18390152/?originalSubdomain=nl
    - name: Thomas Maillart
      role: University of Geneva
      image: experts/thomas.jpg
      linkedin: https://www.linkedin.com/in/thomasmaillart/
    - name: Evangelos Pournaras
      role: University of Leeds
      image: experts/evangelos.jpg
      twitter: https://twitter.com/EPournaras
      linkedin: https://www.linkedin.com/in/epournaras/
    - name: Christoph Laib
      role: VIOS GmbH
      image: experts/Christoph.png
      twitter: https://mobile.twitter.com/claib
      linkedin: https://www.linkedin.com/in/christoph-laib-57444a/
    - name: Chris Salter
      role: Design and Computation Arts
      image: experts/Salter.jpg
    - name: Lilian Blaser
      role: EBP
      image: experts/blaser.jpeg
    - name: Tobias Luthe
      role: ETH
      image: experts/luthe.jpg

section5:
  title: Frequently asked questions
  subtitle: ""
  content_items:
    - question: Do I need to have any specific qualifications to be a participant for the Hackathon?
      answer: If you love to code, prototype hardware solutions, you are more than welcome to participate in the Hackathon.
    - question: How do I submit what I have made for the Hackathon?
      answer: You have to develop the application, software, hardware, etc. on your local system and submit it to https://github.com/ethz-coss along with instructions to run the application and source code.
    - question: Do we need to have the entire idea fully working?
      answer: The entire idea need not be fully implemented however, the submission should be functional (e.g. small scale) so that it can be reviewed by the lecturers.
    - question: Will you provide hardware components, prototypes and DB for us to kick-off on ideas?
      answer: Yes, we will provide standard hardware and more specific hardware on request. We provide sample code and db.
    - question: Do I need to give a demo for the product that I have built?
      answer: Yes, the demo is part of the requirements to earn the ECTS.
    - question: Who will own the IP (Intellectual Property) Rights to the product that I have built?
      answer: The developer/developers of the product will have all rights and own the IP of the product. However, all code needs to be in public domain (open source) so that it can be evaluated by the judges.


section6:
  title: Join us & get started
  text: Sign up and join _ participants!
  signed_up: "37"
  subtitle: Here are a few links to related work and helpful resources
  content_items:
    - title: Paper
      description: "Getting Real: The Challenge of Building and Validating a Large-Scale Digital Twin of Barcelona’s Traffic with Empirical Data"
      url: https://www.mdpi.com/1429762
      fa_icon: newspaper
    - title: Paper
      description: "Participatory resilience: Surviving, recovering and improving together"
      url: https://www.sciencedirect.com/science/article/pii/S2210670722002633?via%3Dihub
      fa_icon: newspaper
    - title: Paper
      description: "Design and development of an open-source framework for citizen-centric environmental monitoring and data analysis"
      url: https://www.nature.com/articles/s41598-022-18700-z
      fa_icon: newspaper
    - title: Repository
      description: Soc-IoT
      url: https://github.com/sachit27/Soc-IoT
      fa_icon: github
    - title: Paper
      description: "Introducing participatory fairness in emergency communication can support self-organization for survival"
      url: https://www.nature.com/articles/s41598-021-86635-y
      fa_icon: newspaper
    - title: SOS Pseudocode
      description: "Pseudocode: Introducing participatory fairness in emergency communication can support self-organization for survival"
      url: https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-021-86635-y/MediaObjects/41598_2021_86635_MOESM1_ESM.pdf
      fa_icon: newspaper


contactform:
  title: Ideas? Feedback? Special requirements? Let us know!
  subtitle: Will you need other material or resources or do you have suggestions. We'd love to hear about them.
  background_image: contactform_background.png




footer:
  vvz_link: http://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?semkez=2022W&lang=de&ansicht=LEHRVERANSTALTUNGEN&lerneinheitId=165358
  moodle_link: https://moodle-app2.let.ethz.ch
  coss_link: https://coss.ethz.ch
  coci_link: https://coss.ethz.ch/research/CoCi.html
  freifunk_link: https://freifunk-3laendereck.net
  erc_link: https://erc.europa.eu/
  footer_text_1: "This course has received funding from the European Research Council (ERC) under the European Union's Horizon 2020 research and innovation programme under grant agreement No. 833168, “CoCi: Co-Evolving City Life”."
  footer_text_2: "Visitors acknowledge that they may be included in audio recordings, photos and video recordings taken during the event or in connection with it, and agree that these may be used without financial compensation or limited in terms of time or location."
  
  image_attributions:
    - name: "'Climate' icon by monkik"
      source_name: The Noun Project
      source_domain: https://thenounproject.com/
      source_url: https://thenounproject.com/icon/climate-2731699/
    - name: Photo by Conny Schneider
      source_name: Unsplash
      source_domain: https://unsplash.com
      source_url: https://unsplash.com/photos/xuTJZ7uD7PI
    - name: Photo by Finn Hackshaw
      source_name: Unsplash
      source_domain: https://unsplash.com
      source_url: https://unsplash.com/photos/FQgI8AD-BSg
    - name: Photo by krakenimages
      source_name: Unsplash
      source_domain: https://unsplash.com
      source_url: https://unsplash.com/photos/Y5bvRlcCx8k
    - name: Photo by Florian Olivo
      source_name: Unsplash
      source_domain: https://unsplash.com
      source_url: https://unsplash.com/photos/4hbJ-eymZ1o
    - name: Photo by Austin Distel
      source_name: Unsplash
      source_domain: https://unsplash.com
      source_url: https://unsplash.com/photos/wD1LRb9OeEo
    - name: Photo by Mario Caruso
      source_name: Unsplash
      source_domain: https://unsplash.com
      source_url: https://unsplash.com/photos/0C9VmZUqcT8
    - name: Photo by Alina Grubnyak
      source_name: Unsplash
      source_domain: https://unsplash.com
      source_url: https://unsplash.com/photos/ZiQkhI7417A
