name: Upload the website to Server for public viewing
on: 
  push:
    branches:
      - production

jobs:
  compile_html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: install pip packages
        run: python -m pip install -r requirements.txt
      - name: copy file to output
        run: python main.py templates out values.yaml
      - name: upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "out/*""
          target: "~/web/"